service: my-function-swapi

provider:
  name: aws
  runtime: nodejs18.x

functions:
  swapi:
    handler: src/handler.swapi
    events:
      - http:
          path: swapi
          method: get